### ISSUE TITLE
.NET System.NotSupportedException on Windows 11 & Python 3.10

### ISSUE THREAD

**Issue by phrozen** [mathoudebine/turing-smart-screen-python#141]
Using Windows 11 latest (2H22) and Python 3.10.7

**Describe the bug**  
Running `simple-program.py` works ("AUTO" port does not work), after configuring the `config.yaml` with the same settings, running `main.py` fails due to .Net Exception.

```
\turing-smart-screen-python-2.2.1 via 🐍 v3.10.7 took 33s
❯ python main.py 
17:05:23 [INFO] Loading theme 3.5inchTheme2 from res/themes/3.5inchTheme2/theme.yaml
17:05:23 [DEBUG] Static COM port: COM4
System.NotSupportedException: An attempt was made to load an assembly from a network location
which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. 
This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. 
If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch.
See http://go.microsoft.com/fwlink
```

When running Python with Admin privileges, I get extra output regarding what I'm assuming has to do with the system monitoring part (loding the library). Any help? Thoughts?

```
\turing-smart-screen-python-2.2.1 via 🐍 v3.10.7
❯ python main.py
17:19:45 [INFO] Loading theme 3.5inchTheme2 from res/themes/3.5inchTheme2/theme.yaml
17:19:45 [DEBUG] Static COM port: COM4
System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\main.py", line 48, in <module>
    import library.scheduler as scheduler
  File "C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\library\scheduler.py", line 28, in <module>
    import library.stats as stats
  File "C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\library\stats.py", line 56, in <module>
    import library.sensors.sensors_librehardwaremonitor as sensors
  File "C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\library\sensors\sensors_librehardwaremonitor.py", line 40, in <module>
    clr.AddReference(lhm_dll)
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\external\LibreHardwareMonitor\LibreHardwareMonitorLib.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\...\Downloads\turing-smart-screen-python-2.2.1\turing-smart-screen-python-2.2.1\external\LibreHardwareMonitor\LibreHardwareMonitorLib.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Python.Runtime.AssemblyManager.LoadAssemblyFullPath(String name)
   at Python.Runtime.CLRModule.AddReference(String name)
```

**Comment by mathoudebine** [comment]
Hi, you can have a look at the Troubleshooting page here https://github.com/mathoudebine/turing-smart-screen-python/wiki/Troubleshooting you will find a fix to this issue
