### ISSUE TITLE
8.8 inch screen support

### ISSUE THREAD

**Issue by arthurv** [mathoudebine/turing-smart-screen-python#264]
I've got the 3.5 inch screen running nicely, and a 5 inch screen is on the way.

However, it seems an 8.8 inch screen is also available, any plans for supporting this?
https://www.aliexpress.com/item/1005005538293555.html

It looks like the perfect screen (in portrait mode) to display a to-do list, for example.

**Comment by mathoudebine** [comment]
Hi! So there is now an 8.8 inch screen, great news but I'll be ruined if they release new models every 6 months 😄
If the protocol is the same as the 5.5 inch screen (which seems to be the case becasue the configuration software looks the same) then supporting it will be quick and easy.
But if they develop a new protocol for the 8.8 inch display, it will require to analyze serial frames like people did for the 5.5 inch so it will take longer.
Anyway, I will order one and we'll see! I would be happy if we can add it to the list of supported displays

**Comment by rastersoft** [comment]
Hi. I see that there is a branch for 8.8 inch screens. I have one. Can I help?

**Comment by Paradoxum** [comment]
Glad people are finding this and getting involed. Is there a discord? would be good to have a channel for example talking about themes etc.

**Comment by ferni7** [comment]
Hey, does the 8 inch branch work? If so I'll order one and have a play...

**Comment by roid1995** [comment]
Hi, i have buy this screen it'is awesome. Can you support him?

**Comment by WanaGo** [comment]
Hi, has there been any progress towards support for the 8.8 inch display? Thanks

**Comment by eamanola** [comment]
+1 interest

**Comment by SRadyukov** [comment]
interest for 2.1 inch support
i tested branch https://github.com/mathoudebine/turing-smart-screen-python/tree/feature/264-88-inch-screen-support
device detected but image currupted - look like smt wrong with bitmap send 
i dont have protocol spec for this device, how i can help?

**Comment by shinyafro** [comment]
+1

**Comment by SolarBlackhole** [comment]
Looking to replace my aida64 8.8 screen with a turing one, definitely interesting in seeing this screen size supported.

**Comment by Tharkus** [comment]
+1 interest

**Comment by WanaGo** [comment]
Hi again @mathoudebine - Do you have any plans to add 8.8 support any time soon, or is this still some time off? I would love to use this, the standard software is a challenge

**Comment by scottrlarson** [comment]
Looking forward to this too. I might have to look into figuring this out I want to turn my 8.8 in screen into a command line program output display for my data recovery jobs.

**Comment by Jim-Wright** [comment]
Just ordered an 8.8 and am interested also.  Haven’t seen anyone mention they’ve tested this branch, guess I’ll have a look when mine gets here.

**Comment by Sonny-Crockett** [comment]
+1 to 8"

**Comment by credmond81** [comment]
Also hoping for 8.8" support soon. Really cool stuff!

**Comment by Jdmoto** [comment]
Any luck on supporting the 8.8 inch?

**Comment by hossamsy** [comment]
If that 8.8 inch usb-only screen work... it is great looking and seems faster than the Turzx 3.5 laggy one

**Comment by nreinartz** [comment]
Also got mine some weeks ago and started working on supporting it. Protocol was slightly changed but I am mostly finished and am currently testing all the functionality by making some example themes that already come with the turzx software. I would also be interested in adding the support for dynamic background videos but it doesn't seem like that has been done for any type of screen yet, so this might be a little more work.

Will do a pr as soon as I am done with the basic support.

**Comment by nreinartz** [comment]
I don't even know what this is, sorry.

Basic Support = Hardware stats
Dynamic Background Videos = Hardware stats with a video as background instead of a static image

**Comment by hossamsy** [comment]
Simhub is simracing app like Aida but it shows the racing game stats on a usb screen, they have support for 3.5 and 5 inches turing in it, but not the 8 inch, it is what all sim racers use to connect dashboard screens and read games data, that is where the money is today

**Comment by Grotok89** [comment]
> Also got mine some weeks ago and started working on supporting it. Protocol was slightly changed but I am mostly finished and am currently testing all the functionality by making some example themes that already come with the turzx software. I would also be interested in adding the support for dynamic background videos but it doesn't seem like that has been done for any type of screen yet, so this might be a little more work.
> 
> Will do a pr as soon as I am done with the basic support.

Unfortunately i could not get it to work
and there is also no test theme for 8.8 right?
tried to modify a theme.yaml and background.
but then i get

Traceback (most recent call last):
  File "C:\lcd\main.py", line 189, in <module>
    display.initialize_display()
  File "C:\lcd\library\display.py", line 95, in initialize_display
    self.lcd.InitializeComm()
  File "C:\lcd\library\lcd\lcd_comm_rev_c.py", line 229, in InitializeComm
    self._hello()
  File "C:\lcd\library\lcd\lcd_comm_rev_c.py", line 211, in _hello
    if response.startswith(SubRevision.FIVEINCH.value):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be str or a tuple of str, not bytearray

**Comment by maylton** [comment]
I want to help with supporting the turing 2.1 screen. How can I help?

**Comment by Mumrikken** [comment]
+1 on support for the 2.1 inch screen!

**Comment by Baho73** [comment]
+1 8.8 inch screen

**Comment by maylton** [comment]
Any update on the 2.1 support?

Em sex., 17 de jan. de 2025, 15:57, Baho73 ***@***.***>
escreveu:

**Comment by kaishi00** [comment]
+1 for 8.8 support! Recently migrated to linux from windows and kinda need this to work :)

**Comment by mathoudebine** [comment]
Hi all
Just to let you know that the support for Turing 2.1" and 8.8" displays is planned for the next release!
The pull request is here #690 
For those who can't wait, you can already try the branch `feature/264-88-inch-screen-support`

**Comment by Tharkus** [comment]
> Olá a todos Só para você saber que o suporte para telas Turing 2.1" e 8,8 está planejado para o próximo lançamento! O pull request está aqui [? 690](https://github.com/mathoudebine/turing-smart-screen-python/pull/690) Para aqueles que não podem esperar, você já pode tentar o branch `feature/264-88-inch-screen-support`

Thank you very much, I've been waiting for this news for months.

**Comment by ferni7** [comment]
Nice! Anyone found it cheaper than the link in the OP abovew?

**Comment by mathoudebine** [comment]
New release 3.9.0 is out with support for 8.8" and 2.1" screens: https://github.com/mathoudebine/turing-smart-screen-python/releases/tag/3.9.0
