### ISSUE TITLE
Unable to detect COM port on Windows 10

### ISSUE THREAD

**Issue by snada88** [mathoudebine/turing-smart-screen-python#37]
**Describe the bug**  

C:\Other Programs\turing-smart-screen-python-2.0.0>python main.py
14:18:45 [INFO] Loading theme 3.5inchTheme2_theme from res/themes/3.5inchTheme2_theme/theme.yaml
14:18:45 [DEBUG] Auto detected COM port: None
Traceback (most recent call last):
  File "C:\xxx\turing-smart-screen-python-2.0.0\main.py", line 56, in <module>
    display.initialize_display()
  File "C:\xxx\turing-smart-screen-python-2.0.0\library\display.py", line 53, in initialize_display
    self.lcd.InitializeComm()
  File "C:\xxx\turing-smart-screen-python-2.0.0\library\lcd_comm_rev_b.py", line 117, in InitializeComm
    self.Hello()
  File "C:\xxx\turing-smart-screen-python-2.0.0\library\lcd_comm_rev_b.py", line 90, in Hello
    self.SendCommand(Command.HELLO, payload=hello, bypass_queue=True)
  File "C:\xxx\turing-smart-screen-python-2.0.0\library\lcd_comm_rev_b.py", line 80, in SendCommand
    self.WriteData(byteBuffer)
  File "C:\xxx\turing-smart-screen-python-2.0.0\library\lcd_comm.py", line 72, in WriteData
    self.lcd_serial.write(bytes(byteBuffer))
  File "C:\Users\xxxx\miniconda3\lib\site-packages\serial\serialwin32.py", line 306, in write
    raise PortNotOpenError()
serial.serialutil.PortNotOpenError: Attempting to use a port that is not open

**To Reproduce**  
1. install requirements using pip
2. connect Turing via USB
3. run python main.py

**Expected behavior**  
I expect the program to start normally

**Screenshots / photos of the Turing screen**  
N/A

**Environment:**  
 - turing-smart-screen-python-2.0.0
 - Microsoft Windows 10 Build 19044
 - Python 3.9.12 (conda)

**Additional context**  
N/A

**Comment by snada88** [comment]
Issue was with physical USB ports.
