### ISSUE TITLE
The parameters(load, temp, memory) of the Intel UHD 770 GPU are not displayed

### ISSUE THREAD

**Issue by ingenegra** [mathoudebine/turing-smart-screen-python#476]
**Describe the bug**  
The parameters(load, temp, memory) of the Intel UHD 770 GPU are not displayed

**To Reproduce**  
1. Run main.py
2. See error in IDLE window

**Expected behavior**  
Correct display of parameters(load, temp, memory) of Intel integrated UHD 770 GPU

**Screenshots / photos of the Turing screen**  
![3081698b-3f0c-489c-81ae-e4b90e4a2ae9](https://github.com/mathoudebine/turing-smart-screen-python/assets/35201371/d1179201-7ee2-4b98-9c09-2724606e5972)

![Новый точечный рисунок (4)](https://github.com/mathoudebine/turing-smart-screen-python/assets/35201371/d146b4db-6c70-4a52-8da2-d73bf7b851bd)

**Environment:**  
 - Smart screen model Turing 5"
 - main.py
 - OS Windows 10
 - Python 3.10.2
 - Hardware Intel CPU I5-3600K,  Intel integrated UHD 770 GPU

**Additional context**  

**Report of test_librehardwaremonitor.py**

---------------------------------------------------------------------------------------
= RESTART: C:\Program Files\Python310\turing-smart-screen-python-main\external\LibreHardwareMonitor\test_librehardwaremonitor.py
Found LibreHardwareMonitorLib 0.9.3.0
Found HidSharp 2.1.0.0
Motherboard | Gigabyte B760I AORUS PRO | /motherboard
    SuperIO | ITE IT8689E | /lpc/it8689e/0
        Control | Fan #1 | None
        Control | Fan #2 | None
        Control | Fan #3 | 50.0
        Control | Fan #4 | None
        Control | Fan #5 | None
        Control | Fan #6 | None
        Voltage | Voltage #1 | 0.7319999933242798
        Voltage | Voltage #2 | 2.0160000324249268
        Voltage | Voltage #3 | 2.003999948501587
        Voltage | Voltage #4 | 2.003999948501587
        Voltage | Voltage #5 | 0.035999998450279236
        Voltage | Voltage #6 | 1.8000000715255737
        Voltage | Voltage #7 | 1.9919999837875366
        Voltage | 3VSB | 3.3359999656677246
        Voltage | VBat | 3.0480000972747803
        Temperature | Temperature #1 | 39.0
        Temperature | Temperature #2 | 40.0
        Temperature | Temperature #3 | 42.0
        Temperature | Temperature #5 | 39.0
        Fan | Fan #1 | 470.3832702636719
        Fan | Fan #2 | 0.0
        Fan | Fan #5 | 5625.0
----------------------------------------------------
Cpu | 13th Gen Intel Core i5-13600K | /intelcpu/0
    Load | CPU Core #1 Thread #1 | 7.540840148925781
    Load | CPU Core #1 Thread #2 | 0.19467473030090332
    Load | CPU Core #2 Thread #1 | 0.5620360374450684
    Load | CPU Core #2 Thread #2 | 0.19320249557495117
    Load | CPU Core #3 Thread #1 | 0.0
    Load | CPU Core #3 Thread #2 | 0.18829107284545898
    Load | CPU Core #4 Thread #1 | 0.0
    Load | CPU Core #4 Thread #2 | 0.06903409957885742
    Load | CPU Core #5 Thread #1 | 0.0
    Load | CPU Core #5 Thread #2 | 0.436168909072876
    Load | CPU Core #6 Thread #1 | 0.0
    Load | CPU Core #6 Thread #2 | 0.43587684631347656
    Load | CPU Core #7 | 5.169338226318359
    Load | CPU Core #8 | 8.006965637207031
    Load | CPU Core #9 | 6.434881687164307
    Load | CPU Core #10 | 5.993861198425293
    Load | CPU Core #11 | 5.561542510986328
    Load | CPU Core #12 | 6.060534477233887
    Load | CPU Core #13 | 5.0996599197387695
    Load | CPU Core #14 | 10.065526008605957
    Load | CPU Total | 2.9331207275390625
    Load | CPU Core Max | 10.065526008605957
    Temperature | CPU Core #1 | 50.0
    Temperature | CPU Core #2 | 37.0
    Temperature | CPU Core #3 | 45.0
    Temperature | CPU Core #4 | 39.0
    Temperature | CPU Core #5 | 37.0
    Temperature | CPU Core #6 | 38.0
    Temperature | CPU Core #7 | 41.0
    Temperature | CPU Core #8 | 41.0
    Temperature | CPU Core #9 | 41.0
    Temperature | CPU Core #10 | 41.0
    Temperature | CPU Core #11 | 39.0
    Temperature | CPU Core #12 | 39.0
    Temperature | CPU Core #13 | 39.0
    Temperature | CPU Core #14 | 39.0
    Temperature | CPU Package | 50.0
    Temperature | CPU Core #1 Distance to TjMax | 50.0
    Temperature | CPU Core #2 Distance to TjMax | 63.0
    Temperature | CPU Core #3 Distance to TjMax | 55.0
    Temperature | CPU Core #4 Distance to TjMax | 61.0
    Temperature | CPU Core #5 Distance to TjMax | 63.0
    Temperature | CPU Core #6 Distance to TjMax | 62.0
    Temperature | CPU Core #7 Distance to TjMax | 59.0
    Temperature | CPU Core #8 Distance to TjMax | 59.0
    Temperature | CPU Core #9 Distance to TjMax | 59.0
    Temperature | CPU Core #10 Distance to TjMax | 59.0
    Temperature | CPU Core #11 Distance to TjMax | 61.0
    Temperature | CPU Core #12 Distance to TjMax | 61.0
    Temperature | CPU Core #13 Distance to TjMax | 61.0
    Temperature | CPU Core #14 Distance to TjMax | 61.0
    Temperature | Core Max | 50.0
    Temperature | Core Average | 40.42856979370117
    Clock | CPU Core #1 | 5091.86083984375
    Clock | CPU Core #2 | 5091.86083984375
    Clock | CPU Core #3 | 1896.9676513671875
    Clock | CPU Core #4 | 1098.2445068359375
    Clock | CPU Core #5 | 1098.2445068359375
    Clock | CPU Core #6 | 1098.2445068359375
    Clock | CPU Core #7 | 1098.2445068359375
    Clock | CPU Core #8 | 1098.2445068359375
    Clock | CPU Core #9 | 798.7232666015625
    Clock | CPU Core #10 | 798.7232666015625
    Clock | CPU Core #11 | 798.7232666015625
    Clock | CPU Core #12 | 798.7232666015625
    Clock | CPU Core #13 | 798.7232666015625
    Clock | CPU Core #14 | 798.7232666015625
    Power | CPU Package | 6.962255954742432
    Power | CPU Cores | 5.703433990478516
    Power | CPU Memory | 0.0
    Voltage | CPU Core | 0.7332763671875
    Voltage | CPU Core #1 | 0.7332763671875
    Voltage | CPU Core #2 | 0.7332763671875
    Voltage | CPU Core #3 | 0.7330322265625
    Voltage | CPU Core #4 | 0.7330322265625
    Voltage | CPU Core #5 | 0.7330322265625
    Voltage | CPU Core #6 | 0.7330322265625
    Voltage | CPU Core #7 | 0.7330322265625
    Voltage | CPU Core #8 | 0.7330322265625
    Voltage | CPU Core #9 | 0.7330322265625
    Voltage | CPU Core #10 | 0.7330322265625
    Voltage | CPU Core #11 | 0.72802734375
    Voltage | CPU Core #12 | 0.72802734375
    Voltage | CPU Core #13 | 0.72802734375
    Voltage | CPU Core #14 | 0.7276611328125
    Clock | Bus Speed | 99.84040832519531
----------------------------------------------------
Memory | Generic Memory | /ram
    Data | Memory Used | 8.22836685180664
    Data | Memory Available | 23.474258422851562
    Load | Memory | 25.954849243164062
    Data | Virtual Memory Used | 9.37307357788086
    Data | Virtual Memory Available | 27.079551696777344
    Load | Virtual Memory | 25.713027954101562
----------------------------------------------------
GpuIntel | Intel(R) UHD Graphics 770 | /gpu-intel-integrated/\\?\PCI#VEN_8086&DEV_A780&SUBSYS_D0001458&REV_04#3&11583659&0&10#{1ca05180-a699-450a-9a0c-de4fbe3ddd89}
    Power | GPU Power | 12.611653327941895
    SmallData | D3D Shared Memory Used | 605.921875
    Load | D3D 3D | 4.135100364685059
    Load | D3D Video Decode | 0.0
    Load | D3D Copy | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Video Decode | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D GDI Render | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Other | 0.0
----------------------------------------------------
Storage | WDC WD20EZRX-00D8PB0 | /hdd/0
    Temperature | Temperature | 33.0
    Load | Used Space | 76.06398010253906
    Load | Read Activity | 4.7513090351003484e-08
    Load | Write Activity | 1.555414286258383e-08
    Load | Total Activity | 99.99989318847656
    Throughput | Read Rate | None
    Throughput | Write Rate | None
----------------------------------------------------
Storage | KINGSTON SFYRS1000G | /nvme/1
    Temperature | Temperature | 38.0
    Level | Available Spare | 100.0
    Level | Available Spare Threshold | 10.0
    Level | Percentage Used | 0.0
    Data | Data Read | 747.0
    Data | Data Written | 1062.0
    Temperature | Temperature 2 | 54.0
    Load | Used Space | 11.160652160644531
    Load | Read Activity | 8.36735523535026e-07
    Load | Write Activity | 5.580279776040697e-07
    Load | Total Activity | 99.99989318847656
    Throughput | Read Rate | None
    Throughput | Write Rate | None
----------------------------------------------------
Network | Ethernet | /nic/{4CCEDF5F-C146-400D-8777-F5884CE97A3D}
    Data | Data Uploaded | 0.008419337682425976
    Data | Data Downloaded | 0.03777995705604553
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 440.5704040527344
    Load | Network Utilization | 0.00035245632170699537
----------------------------------------------------
Network | Беспроводная сеть | /nic/{4B14871D-EE8C-4E71-83E3-18030B34021F}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | Подключение по локальной сети* 10 | /nic/{D3911975-CFC2-4452-9F32-343FF5A3DE44}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | Подключение по локальной сети* 9 | /nic/{60703CD3-42E5-4E5A-9B16-54E57C28168F}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------
Network | Сетевое подключение Bluetooth | /nic/{B9199C0E-357D-4D41-8A18-FE18B0B2F945}
    Data | Data Uploaded | 0.0
    Data | Data Downloaded | 0.0
    Throughput | Upload Speed | 0.0
    Throughput | Download Speed | 0.0
    Load | Network Utilization | 0.0
----------------------------------------------------

**Report of main.py**

-----------------------------------------------------------
== RESTART: C:\Program Files\Python310\turing-smart-screen-python-main\main.py =
23.02.2024 11:58:52 [INFO] Loading theme Landscape15Grid from res/themes/Landscape15Grid/theme.yaml
23.02.2024 11:58:52 [DEBUG] HW revision: C
23.02.2024 11:58:52 [DEBUG] Static COM port: COM7
23.02.2024 11:58:53 [DEBUG] Found LibreHardwareMonitorLib 0.9.3.0
23.02.2024 11:58:54 [INFO] Found CPU: 13th Gen Intel Core i5-13600K
23.02.2024 11:58:54 [INFO] Found Memory: Generic Memory
23.02.2024 11:58:54 [INFO] Found Intel GPU: Intel(R) UHD Graphics 770
23.02.2024 11:58:54 [INFO] Found Storage: WDC WD20EZRX-00D8PB0
23.02.2024 11:58:54 [INFO] Found Storage: KINGSTON SFYRS1000G
23.02.2024 11:58:54 [INFO] Found Network interface: Ethernet
23.02.2024 11:58:54 [INFO] Found Network interface: Беспроводная сеть
23.02.2024 11:58:54 [INFO] Found Network interface: Подключение по локальной сети* 10
23.02.2024 11:58:54 [INFO] Found Network interface: Подключение по локальной сети* 9
23.02.2024 11:58:54 [INFO] Found Network interface: Сетевое подключение Bluetooth
23.02.2024 11:58:54 [DEBUG] Using Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
23.02.2024 11:58:54 [INFO] Tray icon has been displayed
23.02.2024 11:58:54 [INFO] Display reset (COM port may change)...
23.02.2024 11:59:09 [DEBUG] Static COM port: COM7
23.02.2024 11:59:09 [WARNING] Display returned unknown sub-revision on Hello answer (b'chs_5inch.dev1_rom1.88\x00')
23.02.2024 11:59:09 [DEBUG] HW sub-revision: SubRevision.UNKNOWN
23.02.2024 11:59:10 [INFO] Calling ScreenOn
23.02.2024 11:59:10 [DEBUG] Drawing Image: BACKGROUND
23.02.2024 11:59:10 [DEBUG] Bitmap res/themes/Landscape15Grid/background_grid.png is now loaded in the cache
23.02.2024 11:59:10 [DEBUG] Drawing Text: CPULOAD
23.02.2024 11:59:10 [DEBUG] Drawing Text: CPUTEMP
23.02.2024 11:59:10 [DEBUG] Drawing Text: CPUCLOCK
23.02.2024 11:59:10 [DEBUG] Drawing Text: GPULOAD
23.02.2024 11:59:10 [DEBUG] Drawing Text: GPUTEMP
23.02.2024 11:59:10 [DEBUG] Drawing Text: GPURAM
23.02.2024 11:59:10 [DEBUG] Drawing Text: RAMLOAD
23.02.2024 11:59:10 [DEBUG] Drawing Text: RAMFREE
23.02.2024 11:59:10 [DEBUG] Drawing Text: ETHDOWN
23.02.2024 11:59:10 [DEBUG] Drawing Text: ETHUP
23.02.2024 11:59:10 [DEBUG] Drawing Text: WLDOWN
23.02.2024 11:59:10 [DEBUG] Drawing Text: WLUP
23.02.2024 11:59:10 [DEBUG] Drawing Text: DISKLOAD
23.02.2024 11:59:10 [DEBUG] Drawing Text: DISKFREE
23.02.2024 11:59:10 [DEBUG] Found one supported GPU: Intel(R) UHD Graphics 770
Exception in thread CPU_FanSpeed:
Traceback (most recent call last):
23.02.2024 11:59:10 [WARNING] Your GPU memory absolute usage (M) is not supported yet
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
23.02.2024 11:59:10 [WARNING] Your GPU load is not supported yet
    self.run()23.02.2024 11:59:10 [WARNING] Your GPU temperature is not supported yet

  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python310\turing-smart-screen-python-main\library\scheduler.py", line 73, in wrap
    periodic(scheduler, interval, func)
  File "C:\Program Files\Python310\turing-smart-screen-python-main\library\scheduler.py", line 64, in periodic
    action(*actionargs)
  File "C:\Program Files\Python310\turing-smart-screen-python-main\library\scheduler.py", line 118, in CPUFanSpeed
    stats.CPU.fan_speed()
  File "C:\Program Files\Python310\turing-smart-screen-python-main\library\stats.py", line 307, in fan_speed
    fan_percent = sensors.Cpu.fan_percent()
  File "C:\Program Files\Python310\turing-smart-screen-python-main\library\sensors\sensors_librehardwaremonitor.py", line 238, in fan_percent
    return float(sensor.Value)
TypeError: float() argument must be a string or a real number, not 'NoneType

**Comment by mathoudebine** [comment]
Hi, thanks for raising this issue. I do not have an Intel GPU at home so couldn't test it.
Your GPU offers these sensors through LibreHardwareMonitor:
```
----------------------------------------------------
GpuIntel | Intel(R) UHD Graphics 770 | /gpu-intel-integrated/\\?\PCI#VEN_8086&DEV_A780&SUBSYS_D0001458&REV_04#3&11583659&0&10#{1ca05180-a699-450a-9a0c-de4fbe3ddd89}
    Power | GPU Power | 12.611653327941895
    SmallData | D3D Shared Memory Used | 605.921875
    Load | D3D 3D | 4.135100364685059
    Load | D3D Video Decode | 0.0
    Load | D3D Copy | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Video Decode | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D Other | 0.0
    Load | D3D GDI Render | 0.0
    Load | D3D Video Processing | 0.0
    Load | D3D Other | 0.0
```
Usually AMD/Nvidia GPUs have a "GPU Core" sensor for GPU global usage. Here it is not available for your Intel GPU but the "D3D 3D" sensor can be used instead. It will be less precise than a "GPU Core" sensor but this is all we have.

For the memory usage the "D3D Shared Memory Used" can be used.

Unfortunately there is no temperature sensor available for your GPU.

I will make a pull request for the GPU usage and GPU memory usage to fix it.

**Comment by mathoudebine** [comment]
The issue should be fixed on `main` branch! Can you give it a try?

**Comment by mathoudebine** [comment]
You just need to download the project again from the main branch to get the latest changes: you can do this from the Github homepage or using this direct link: https://github.com/mathoudebine/turing-smart-screen-python/archive/refs/heads/main.zip

**Comment by ingenegra** [comment]
Hi! I reload files from Github. I took screenshots of the windows10 utility, intel utility and test_librehardwaremonitor. The 5" display showed the download corresponding to the number displayed in the Windows 10 utility in the 3d window. But the GPU load is considered differently. Screenshots attach -- С уважениемВячеслав Атрощенко   27.02.2024, 00:38, "Matthieu Houdebine" ***@***.***>: You just need to download the project again from the main branch to get the latest changes: you can do this from the Github homepage or using this direct link: https://github.com/mathoudebine/turing-smart-screen-python/archive/refs/heads/main.zip—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
