### ISSUE TITLE
NumPy 2.x and newbyteorder

### ISSUE THREAD

**Issue by RuebeDo** [mathoudebine/turing-smart-screen-python#578]
**Describe the bug**  
26.09.2024 07:43:36 [DEBUG] Drawing Image: BACKGROUND
26.09.2024 07:43:36 [DEBUG] Bitmap res/themes/BigClock/background.png is now loaded in the cache
Traceback (most recent call last):
  File "/turing-smart-screen-python-main/main.py", line 192, in module display.display_static_images()
  File "/turing-smart-screen-python-main/library/display.py", line 113, in display_static_images self.lcd.DisplayBitmap(
  File "/turing-smart-screen-python-main/library/lcd/lcd_comm.py", line 205, in DisplayBitmap self.DisplayPILImage(image, x, y, width, height)
  File "/turing-smart-screen-python-main/library/lcd/lcd_comm_rev_a.py", line 234, in DisplayPILImage rgb565le = self.imageToRGB565LE(image)
  File "/turing-smart-screen-python-main/library/lcd/lcd_comm_rev_a.py", line 199, in imageToRGB565LE return rgb565.newbyteorder('<').tobytes()
AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.
26.09.2024 07:43:36 [INFO] Program will now exit
26.09.2024 07:43:36 [INFO] Waiting for all pending request to be sent to display (5s max)...
26.09.2024 07:43:41 [DEBUG] (5.1s)

**To Reproduce**  
1. Start the script

**Expected behavior**  
Script starts with NumPy 2.x

**Environment:**  
 - Smart screen model: Smart Screen 3.5"
 - Revision of this project: 3.5.0, main branch, latest commit
 - OS with version: Kubuntu 24.04
 - Python version: Python 3.12.3, NumPy 2.1.1
 - Hardware: Intel® Core™ i5-7300U CPU @ 2.60GHz, Mesa Intel® HD Graphics 620

**Comment by mathoudebine** [comment]
Hello @RuebeDo
Indeed numpy 2.x is not supported for now. You need to use the specified version of numpy from `requirements.txt`:

https://github.com/mathoudebine/turing-smart-screen-python/blob/4ca1f5ffe49dc3deafee210498294749f95d19ec/requirements.txt#L15

See here to install requirements from requirements.txt: https://github.com/mathoudebine/turing-smart-screen-python/wiki/System-monitor-%3A-how-to-start#3-install-python-dependencies

**Comment by mathoudebine** [comment]
Hi @RuebeDo
Numpy 2.x support is now implemented on main branch and will be included on the next release
