### ISSUE TITLE
Screen displays corrupted images on Mac

### ISSUE THREAD

**Issue by opless** [mathoudebine/turing-smart-screen-python#7]
Someone else has had a similar issue here:

https://youtu.be/4z5OOW1jL94

I’m also using an M1 Mac.

I’m also reverse engineering the vendor .net binaries to attempt to figure out what is going wrong.

Though I’m struggling a little with the obfuscation. 😂

it’s not something as simple as endian issues!

**Comment by opless** [comment]
Looks like it's something weird with the serial comms or the operating system.

Closing because it's not fixable here.

**Comment by mathoudebine** [comment]
Sorry to hear that, FYI the display you should expect is this one: https://www.youtube.com/watch?v=Y1m4KK881Aw
I had greater success in decompiling the chinese binary than the english one, it was not obfuscated. You will find the link of it in the README

**Comment by opless** [comment]
I've had a look at all three, and yes, the one you mention is MUCH easier to work with.

It's a shame there's no way to get hold of the creators and have a look at their firmware source.

I'm considering knocking something up in golang, to see if it's just the serial port drivers are broken on the M1 or if it's just pyserial that's not working.

**Comment by alanrenouf** [comment]
Im also getting this issue on my Mac, dont get it on windows.  the port shows up as "/dev/tty.usbmodemUSB35INCHIPSV21" @opless did you find a workaround ?

**Comment by opless** [comment]
It's very much to do with the USB serial implementation, as far as I can tell.

I had some better luck sending data to it via golang, as the serial port initialisation is different. 

I pretty much put the project aside after things getting busy with the day job and having less brain in the evening. It's certainly something weird with the M1 serial usb drivers though!

**Comment by mathoudebine** [comment]
Hi, i'm reopening this issue for people with Mac that have the same problem. Feel free to discuss here. What you can also try is changing the COM port settings here: https://github.com/mathoudebine/turing-smart-screen-python/blob/deb0a60b772f2c5acef377f13b959632ca649f9f/main.py#L184
If i remember correctly, the display also works with baudrates slower than 115200

**Comment by Ebag333** [comment]
https://github.com/mathoudebine/turing-smart-screen-python/pull/15

I think I've fixed it by serializing the updates to the screen (using a queue, so it'll run through each one cleanly before executing the next).

With the default code base I could get it to step on itself, once I started adding a bunch more things to update it just got worse and worse.  You could help by increasing the delay after an update was done, but slowing down the updates isn't really a solution as it makes everything slow.

With this PR it runs at a very high rate and has no issues with keeping up, not getting serial errors anymore.

**Comment by gerph** [comment]
From my own investigation:

In my testing in my own library, I found that the delay between the bitmap data being output and the next command being issued needs to be quite long - about 0.02 seconds. Shorter than this and you get corruption on the display. The current delay in the code on the master branch is about 0.01 seconds, which means that the other slack is being taken up by the code sitting between the `time.sleep(0.01)` and the next `SendReg` writing a command. On faster machines that code will be executed faster, and result in the corruption (I believe).

In my library I changed the behaviour so that instead of explicitly sleeping at the end of the update of a bitmap, we remember when the last output happened and if we try to write a command before the required inter-bitmap-delay has expired, we sleep there instead. This means that we get useful work done between the two operations, and if you did enough work you'd never need to sleep at all before the next command was written.

My library changes that did this were here, if they're useful to you:

https://github.com/gerph/turing-smart-screen-python-mit/commit/8ba5901224ba5e52c37e86e668f73eca4d890b4d

It looks like the changes in PR #15, mentioned above, move the logic for the delay out of the communications library. I cannot tell how this keeps the bitmap transfers and the subsequent command updates apart enough to avoid the corruption.

**Comment by gerph** [comment]
I've tried out the feature/system-monitor branch, at f3748418c42, with flagship display, on my macOS system... I tried running the main a few times, and observed corruption on each of them - the first run generally doesn't even display the main image. The main image also appears offset for some reason.


https://user-images.githubusercontent.com/13813876/187958553-226441df-aeb4-486d-be07-a797d872448a.mp4

I'm not sure why it's doing that, but that's what I've seen with it so far - I may try and investigate later.

I suspect there's some race in the lcd_comm library - looking at lcd_comm_reb_b.py line 197, I see that we issue a SendCommand DISPLAY_BITMAP without the bypass_queue, and then go into loading the image and try to send it. Because bypass_queue wasn't set, the DISPLAY_BITMAP may not have been sent yet and the data for to send to the device may have been may get sent first. Additionally, the WriteData command *isn't* protected by the mutex, so it's possible that the queued data gets send DURING the image bitmap data.

**Comment by gerph** [comment]
Oh, I'm wrong about the data being sent during the bitmap update - SendLine is a queue operation, so it should be queued after the DISPLAY_BITMAP command. However, I think there's still a possibility that the SendCommand could be issued then something else get inbetween it and the data from the scheduler.

I'm really not at all convinced that this queue is the right way to go - for a start the queue code mixes the application-specific clients with the general queue dispatch, which means that if you want to re-use this code you have to copy out the queue handler code. And in any case, I'm not sure that it helps with any corruption problems at all.

**Comment by gerph** [comment]
I've tried replacing the queuing code with a simpler mutex-around-atomic operations with delay between the bitmap and next command. This has been solid on my flagship device. Unfortunately I cannot speak to the model A device... but I've tried making the necessary changes - it might not work at all on those models, and there might be a completely different processing model causing the problems there.

Here's the video of it working (again, tested 4 times to be sure it's not a fluke):

https://user-images.githubusercontent.com/13813876/188019709-de91bbd3-a9c6-45a7-8725-8c15cda36e8c.mp4

PR raised with the way that it worked for me. I've ordered a model A, but it'll be a while until it gets here.

https://github.com/mathoudebine/turing-smart-screen-python/pull/34

**Comment by gerph** [comment]
It still might be useful in some cases to have the serial comms on a separate thread, so it's possible the queue could be useful for that. However, that is still a bit complicated, and I didn't attempt it.

**Comment by Bobrobot1** [comment]
I have this issue as well, M1 Pro

**Comment by SaplingLTD** [comment]
Im facing same problem with the last version in MacOS. Trying to figure out why it happened.
![Untitled (1)](https://user-images.githubusercontent.com/31794066/201520901-55622044-3501-4221-8d09-adacaa2b29a3.png)

**Comment by gerph** [comment]
Oooh, it's built into a keyboard?! Is that a custom build or something that others can get hold of? (sorry I still don't know why there's corruption, though :-( )

**Comment by SaplingLTD** [comment]
So far, I can run the python code normally to connect and give command to the screen.
I also tried to use this software on Windows https://wiki.keebmonkey.com/en/products/kbmscreen. It is recommended by the keyboard marker. And it worked fine.

**Comment by mathoudebine** [comment]
Hi @SaplingLTD and welcome to this project

We didn't know the screen had been embedded into a keyboard! Looks really nice
Can you try to use the branch `fix/replace-queued-data-send-with-immediate-plus-deferred-delay` instead of `main` branch? It should solve the issue with MacOS

It is actually in PR #60 because of issues when the program stops: sometimes after a relaunch the screen is in an invalid state and the program crashes. When relaunched again it will then work.

**Comment by amiltonjr** [comment]
@mathoudebine I just tested the branch `fix/replace-queued-data-send-with-immediate-plus-deferred-delay` in MacOS Ventura 13.1 with a `Revision A` display and it did not corrupt the display info! I think merging/rebasing it to the main will get it fixed and running with networking / GPU monitoring. @gerph if you do that, please let me know, then I'll test it out as well.

**Comment by phuongboss** [comment]
Confirmmed the branch `fix/replace-queued-data-send-with-immediate-plus-deferred-delay` fix the screen shuttering on macOS.

**Comment by itsWobble** [comment]
I tried using the branch #60 I'm getting a COMM error "00:06:31 [ERROR] Cannot find COM port automatically, please set it manually in config.yaml".

**Comment by nukdokplex** [comment]
Got this on Manjaro Linux
![IMG20230528205851](https://github.com/mathoudebine/turing-smart-screen-python/assets/25458915/bda6ca4b-4baf-43de-a946-4c971cf8e55e)

Here is logs:
```
мая 28 20:42:08 ndp-desktop python3[616]: 28.05.2023 20:42:08 [WARNING] Tray icon is not supported on your platform
мая 28 20:42:08 ndp-desktop python3[616]: 28.05.2023 20:42:08 [INFO] Display reset (COM port may change)...
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Auto detected COM port: /dev/ttyACM0
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [INFO] HW revision A does not support backplate LED color setting
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Image: BACKGROUND
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: CPU_MODEL
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: GPU_MODEL
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: RAM_MODEL
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: DOWNLOAD_RATE
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: UPLOAD_RATE
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [DEBUG] Drawing Text: DISK_USAGE
мая 28 20:42:13 ndp-desktop python3[616]: 28.05.2023 20:42:13 [INFO] Detected AMD GPU(s)
мая 28 20:50:44 ndp-desktop python3[616]: Exception in thread Queue_Handler:
мая 28 20:50:44 ndp-desktop python3[616]: Traceback (most recent call last):
мая 28 20:50:44 ndp-desktop python3[616]:   File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 621, in write
мая 28 20:50:44 ndp-desktop python3[616]:     n = os.write(self.fd, d)
мая 28 20:50:44 ndp-desktop python3[616]: OSError: [Errno 5] Ошибка ввода/вывода
мая 28 20:50:44 ndp-desktop python3[616]: During handling of the above exception, another exception occurred:
мая 28 20:50:44 ndp-desktop python3[616]: Traceback (most recent call last):
мая 28 20:50:44 ndp-desktop python3[616]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
мая 28 20:50:44 ndp-desktop python3[616]:     self.run()
мая 28 20:50:44 ndp-desktop python3[616]:   File "/usr/lib/python3.10/threading.py", line 953, in run
мая 28 20:50:44 ndp-desktop python3[616]:     self._target(*self._args, **self._kwargs)
мая 28 20:50:44 ndp-desktop python3[616]:   File "/opt/turing/library/scheduler.py", line 74, in wrap
мая 28 20:50:44 ndp-desktop python3[616]:     scheduler.run()
мая 28 20:50:44 ndp-desktop python3[616]:   File "/usr/lib/python3.10/sched.py", line 151, in run
мая 28 20:50:44 ndp-desktop python3[616]:     action(*argument, **kwargs)
мая 28 20:50:44 ndp-desktop python3[616]:   File "/opt/turing/library/scheduler.py", line 64, in periodic
мая 28 20:50:44 ndp-desktop python3[616]:     action(*actionargs)
мая 28 20:50:44 ndp-desktop python3[616]:   File "/opt/turing/library/scheduler.py", line 163, in QueueHandler
мая 28 20:50:44 ndp-desktop python3[616]:     f(*args)
мая 28 20:50:44 ndp-desktop python3[616]:   File "/opt/turing/library/lcd/lcd_comm.py", line 99, in WriteData
мая 28 20:50:44 ndp-desktop python3[616]:     self.lcd_serial.write(bytes(byteBuffer))
мая 28 20:50:44 ndp-desktop python3[616]:   File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 655, in write
мая 28 20:50:44 ndp-desktop python3[616]:     raise SerialException('write failed: {}'.format(e))
мая 28 20:50:44 ndp-desktop python3[616]: serial.serialutil.SerialException: write failed: [Errno 5] Ошибка ввода/вывода
```

**Comment by evilpete** [comment]
I am seeing the issue, exactly like @SaplingLTD 

MacAir  (Intel Core i5) Monterey 12.6.8

**Comment by katanza12** [comment]
Same issue: MacBook Pro M1 Sonoma 14.0. I tried to remove background image, dynamic text and other graphics, put only a static text (starting with simple.program.py) but without success.

**Comment by a3rosol** [comment]
I'll pile on. M1 Ultra. I had to specify the com_port manually and it didn't work with the tty device but seems to work most of the time with the cu device. you can find them using `ls /dev/{tty,cu}.*` mine shows up as `/dev/cu.usbmodemUSB35INCHIPSV21	`. But no matter which theme I chose, I always get artifacts on the screen when refreshes happen.

**Comment by jeffsf** [comment]
Similar defects being seen on macOS 14.4.1 (Sonoma) and Intel in #512 

If I've found the right object, changing from RTS/CTS to DSR/DTR did not seem to change the behavior

```
    # jmk -- try adjusting serial parameters
    lcd_serial: serial.serialposix.Serial = display.lcd.lcd_serial
    from pprint import pprint
    pprint(lcd_serial.get_settings())
    lcd_serial.rtscts = False
    lcd_serial.dsrdtr = True
    pprint(lcd_serial.get_settings())

    # Initialize the display
    display.initialize_display()
```

**Comment by Numbski** [comment]
Just chiming in - I am on an intel mac and getting this exact same behavior, so it isn't a CPU issue.

**Comment by Numbski** [comment]
Silly question - could it be the baud rate?  Per the documentation, none of this is plain text.  We're generating bitmaps and then pushing them to the serial port.  Could be that the bitmap gets corrupted in the transfer process?

**Comment by opless** [comment]
It's something to do with the mac drivers, I'm sure.

**Comment by oldirtdog** [comment]
Chiming in... I'm getting the same issue on my M3 Max... I'm pretty stuck here... sounds like this might not be for Mac folks :(

<img width="286" alt="image" src="https://github.com/user-attachments/assets/01ad2638-f4bf-43a8-8ab6-dd87617d053a" />

**Comment by gregsadetsky** [comment]
M1 Max here, macOS 12.7. Running `simple-program.py` from the latest release (3.7.0) of this software shows this:

<img width="546" alt="image" src="https://github.com/user-attachments/assets/920e92e2-af62-4a3e-b108-585d6ae00060" />

I tried the #60 PR code but that did not work either. thanks a lot!

**Comment by gregsadetsky** [comment]
hey all, I've spent a good chunk of time debugging this. it's not an easy problem (and it isn't fully fixed) but hopefully what I found can help make some progress towards fixing this.

I'm using a simplified version of [simple-program.py](https://github.com/mathoudebine/turing-smart-screen-python/blob/main/simple-program.py) to show [this image](https://github.com/mathoudebine/turing-smart-screen-python/blob/main/res/backgrounds/example_480x320.png)

I used to get a very [corrupted](https://github.com/user-attachments/assets/920e92e2-af62-4a3e-b108-585d6ae00060) image (see my comment just above). now I get this:

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/75956203-29e3-4a29-97cd-18e04182bacb" />

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/c26f6db7-8d65-4601-b6d6-54e5c381b610" />

there are a few things to notice: although the image is "correct" horizontally speaking, vertically, its height is double of the original. looking at the image: you'll see 15 "columns" (15 * 32 = 480, the width here). the columns 0, 3, 5, etc (if we're 0-indexed) are actually on a different vertical line than columns 1, 2, 4, etc. - this is why the height is doubled.

you can see/get my code here: https://github.com/gregsadetsky/turing-smart-screen-python

I've hacked it enough that it will probably only work for showing full images (i.e. it won't work for `DisplayText` etc. calls that only draw to a portion of the screen). in any case, it's still not completely fixed, but hopefully this can shed a light.

the interesting/most hacked bits are [in serial_write](https://github.com/gregsadetsky/turing-smart-screen-python/blob/main/library/lcd/lcd_comm.py#L137).

clearly... some macos usb/serial buffering is interfering with the display's chip. as noted in my comment above, I ran simple-program.py on a raspberry pi and it worked perfectly straight out of the box. (it was frustrating to see, but I'm happy for anyone using linux!)

**Comment by phucynwa** [comment]
@gregsadetsky Can I run it directly from my Mac without using VituralBox ?

**Comment by mathoudebine** [comment]
Hi everyone!

I may have fixed the issue with this simple change on the serial communication:
https://github.com/mathoudebine/turing-smart-screen-python/pull/721/commits/ac169f375b20aa33421ab1ccbf7d130a5eaf0504

By manually flushing the serial buffer regularly, it has solved the corruption problem on my setup:
- MacBook Air (13-inch, 2017)
- macOS Monterrey 12.7.6

A pull request has been opened with this fix here: #721 

Before merging, I would like to have your feedback, especially for people with Apple M1 CPU.
You can use the branch `fix/7-screen-displays-corrupted-images-on-mac` or just apply the on-line fix manually.

Thanks!

**Comment by mathoudebine** [comment]
Reopened because some corruptions still occur

**Comment by mathoudebine** [comment]
@gregsadetsky @oldirtdog what display do you have? Is it a Turing rev. A?
Can you try with some portrait content if possible? Thanks

**Comment by gregsadetsky** [comment]
It's a Rev A yeah. I've been using simple-program.py for all of my tests, should I have been using some other sample code? thanks!

**Comment by tapsu01** [comment]
I get this on MacOS Ventura 13.7.5:
![Image](https://github.com/user-attachments/assets/34b2d30b-6a32-4d0e-9608-cc3c057b1011)

**Comment by oldirtdog** [comment]
Tried in portrait mode... same garbage showing up on screen.

**Comment by aptonline** [comment]
Can I confirm if it's just revision A displays that have this issues or is it all displays?

**Comment by oldirtdog** [comment]
I'll be honest, I got tired of messing around with this thing and threw it in the trash.  I only had the Revision A display.

**Comment by marcelors27** [comment]
I investigated image corruption on macOS with a TURZX/Turing/UsbMonitor 3.5" device and found a likely root cause/workaround.

## Device

- macOS on Apple Silicon
- Device appears as serial:
  - `/dev/cu.usbmodemUSB35INCHIPSV21`
- USB metadata:
  - Manufacturer: `Turing`
  - Product: `UsbMonitor`
  - Serial: `USB35INCHIPSV2`
  - VID/PID: `1a86:5722`

## Symptom

Using the current Rev A serial backend, the display receives data but complex images are corrupted/glitched:

- shifted lines
- repeated blocks
- broken colors
- framebuffer-like misalignment

Simple solid color band patterns can appear mostly correct, which initially makes the serial path look valid, but real theme images are corrupted.

## What I tested

- Python/pyserial Rev A serial backend: corrupted
- Same protocol reimplemented in Go via `/dev/cu.usbmodem...`: corrupted
- Smaller chunks / delays / flushing / skipping HELLO: still corrupted
- Rev B protocol: device does not respond
- Windows vendor software: works correctly

I captured the Windows USB traffic with USBPcap. The payload is standard RGB565 little-endian and matches the Rev A framebuffer format. The key difference is transport:

- Windows sends data directly to USB bulk OUT endpoint `0x03`
- macOS serial path goes through `/dev/cu.usbmodem...`

When I bypassed the macOS serial device and wrote directly to USB bulk endpoint `0x03` using PyUSB/libusb, the image rendered correctly.

## Conclusion

For this device, the framebuffer/protocol is not the issue. The corruption seems to come from the macOS USB CDC serial path. Writing directly to the bulk endpoint fixes it.

## Working approach

Use PyUSB/libusb and write to:

- VID/PID: `1a86:5722`
- interface: CDC data interface `1`
- OUT endpoint: `0x03`
- framebuffer: RGB565 little-endian
- resolution: `320x480`

Minimal flow:

1. Claim interface 1
2. Send Rev A `SET_ORIENTATION`
3. Send Rev A `DISPLAY_BITMAP`
4. Send full RGB565 framebuffer to endpoint `0x03`

This works on macOS for the `USB35INCHIPSV2` device where `/dev/cu.usbmodem...` corrupts images.

This suggests the project may need a macOS-specific backend for Rev A UsbMonitor devices that uses raw USB bulk instead of pyserial.

**Comment by gregsadetsky** [comment]
@marcelors27 amazing work! Would you be able to share what code worked for you on macos?

**Comment by marcelors27** [comment]
Sure. What worked for me on macOS was bypassing `/dev/cu.usbmodem...` entirely and writing directly to the USB bulk OUT endpoint with PyUSB/libusb.

My device is:

- VID/PID: `1a86:5722`
- Manufacturer: `Turing`
- Product: `UsbMonitor`
- Serial: `USB35INCHIPSV2`
- Working OUT endpoint: `0x03`
- Resolution: `320x480`
- Pixel format: RGB565 little-endian

Minimal example:

```python
import time
from PIL import Image
import usb.core
import usb.util

VID = 0x1A86
PID = 0x5722
INTERFACE = 1
OUT_ENDPOINT = 0x03

CMD_SET_ORIENTATION = 121
CMD_DISPLAY_BITMAP = 197

WIDTH = 320
HEIGHT = 480


def rgb565le(image):
    image = image.convert("RGB")
    out = bytearray()
    for r, g, b in image.getdata():
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out += value.to_bytes(2, "little")
    return bytes(out)


def send_command(endpoint, cmd, x, y, ex, ey):
    buf = bytearray(6)
    buf[0] = x >> 2
    buf[1] = ((x & 3) << 6) + (y >> 4)
    buf[2] = ((y & 15) << 4) + (ex >> 6)
    buf[3] = ((ex & 63) << 2) + (ey >> 8)
    buf[4] = ey & 255
    buf[5] = cmd
    endpoint.write(bytes(buf), timeout=5000)


def set_orientation(endpoint):
    buf = bytearray(16)
    buf[5] = CMD_SET_ORIENTATION
    buf[6] = 100  # portrait
    buf[7] = WIDTH >> 8
    buf[8] = WIDTH & 255
    buf[9] = HEIGHT >> 8
    buf[10] = HEIGHT & 255
    endpoint.write(bytes(buf), timeout=5000)


dev = usb.core.find(idVendor=VID, idProduct=PID)
if dev is None:
    raise RuntimeError("Display not found")

try:
    dev.set_configuration()
except usb.core.USBError:
    pass

try:
    if dev.is_kernel_driver_active(INTERFACE):
        dev.detach_kernel_driver(INTERFACE)
except Exception:
    pass

usb.util.claim_interface(dev, INTERFACE)

cfg = dev.get_active_configuration()
intf = usb.util.find_descriptor(cfg, bInterfaceNumber=INTERFACE)

endpoint = usb.util.find_descriptor(
    intf,
    custom_match=lambda ep:
        usb.util.endpoint_direction(ep.bEndpointAddress) == usb.util.ENDPOINT_OUT
        and ep.bEndpointAddress == OUT_ENDPOINT
)

if endpoint is None:
    raise RuntimeError("OUT endpoint not found")

image = Image.open("background.png").convert("RGB").resize((WIDTH, HEIGHT))

set_orientation(endpoint)
time.sleep(0.05)

send_command(endpoint, CMD_DISPLAY_BITMAP, 0, 0, WIDTH - 1, HEIGHT - 1)
time.sleep(0.02)

endpoint.write(rgb565le(image), timeout=5000)

usb.util.release_interface(dev, INTERFACE)
usb.util.dispose_resources(dev)
```

On macOS I also needed libusb:

```
brew install libusb
```

The important finding is that the framebuffer/protocol itself was correct. The corruption happened when using the macOS serial device (/dev/cu.usbmodemUSB35INCHIPSV21). Sending the same RGB565 little-endian framebuffer directly to USB bulk endpoint 0x03 fixed the corrupted image for me.

**Comment by amarok30** [comment]
**Root cause found + verified working fix on macOS** (Mac mini M4, macOS 26.5.2, Turing/UsbMonitor 3.5" rev A — `1a86:5722`, serial `USB35INCHIPSV2`).

After a systematic reverse-engineering session (solid fills, gradients, per-packet rainbow maps, barcode-tagged bands, full USB descriptor probing), the corruption mechanism is now clear:

**The panel firmware is USB-transfer-oriented, not byte-stream-oriented.**

- It reads a command from the **start of a USB transfer** and **ignores the rest of that transfer**.
- After a `DISPLAY_BITMAP` header, it **counts exactly `w*h` pixel bytes** (RGB565 LE). Any byte arriving before the rectangle is complete — including what we believe are commands — is swallowed as pixel data.
- Once the byte stream loses sync (a single lost/mis-framed byte), the panel's pixel counter is off, and **every subsequent command is eaten as pixels** → permanent corruption until power cycle. This explains why RESET/CLEAR "don't work" once the image is corrupted, and why every run produces different garbage.
- The macOS CDC ACM serial path (`/dev/cu.usbmodemUSB35INCHIPSV21`) **repackages/fragments USB transfers arbitrarily**, so commands end up glued to pixel data or split mid-command → instant desync. This matches @gregsadetsky's 64-byte packet reordering observations and why Linux/Windows/ESP32 are unaffected.

These exact semantics are documented in [@tanakamasayuki's EspUsbHost `TuringDevice.hpp`](https://github.com/tanakamasayuki/EspUsbHost/blob/main/examples/Serial/EspUsbHostDisplayTuring/TuringDevice.hpp) (ESP32 USB-host driver for this same panel): *"The panel takes a command from the start of a transfer and ignores the rest of it"* / *"The panel counts the pixels itself"*.

**Working fix (verified end-to-end):** bypass the serial device entirely — write directly to bulk OUT endpoint `0x03` via PyUSB/libusb with strict transfer discipline:

1. every command in its **own transfer** (one `endpoint.write()` per command; a header never shares a transfer with pixel data),
2. `SET_ORIENTATION` is **11 bytes** (6-byte command + orientation+100 + width/height BE), not 16,
3. pixel data in 64-byte-aligned chunks totalling **exactly** `w*h*2` bytes,
4. nothing else is written while a bitmap is in progress,
5. if the panel ever desyncs, unplug/replug the USB-C cable — RESET only reaches the panel when the stream is in sync.

With this, the panel renders solid full-screen frames back-to-back with zero desync, and the full system monitor (themes + live stats) runs correctly on macOS.

A ready-to-use backend (subclass of `LcdCommRevA`, registered as `REVISION: A_USBMAC`) is here: https://gist.github.com/amarok30/cddaa9a9818d6830a74d9332f501047e

Note: @marcelors27's one-shot bulk write worked on their unit but not on ours (identical VID/PID/serial), there seem to be firmware batch differences; the strict transfer discipline above is what made it reliable here. Hope this helps finally close this one .
